-- Drop everything for a fresh start
DROP TABLE IF EXISTS enrichment_log CASCADE;
DROP TABLE IF EXISTS relations CASCADE;
DROP TABLE IF EXISTS note_entities CASCADE;
DROP TABLE IF EXISTS entities CASCADE;
DROP TABLE IF EXISTS agent_state CASCADE;
DROP TABLE IF EXISTS notes CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS _migrations CASCADE;
DROP FUNCTION IF EXISTS match_notes CASCADE;

-- Refresh PostgREST
NOTIFY pgrst, 'reload schema';
